services:
  app:
    image: worker-managment
    build:
      context: .
      dockerfile: PokemonTryASP/Dockerfile
    depends_on:
      - database
    ports:
      - "80:8080"
    networks:
      - backend
    restart: always
    environment: 
      - ASPNETCORE_ENVIRONMENT='Development'
  database:
    image: postgres:16
    restart: always
    environment:                  
      POSTGRES_USER: 'admin'     
      POSTGRES_PASSWORD: 'admin' 
      POSTGRES_DB: 'dotnettest'   
    networks:
      - backend
    ports:
      - "5431:5432"               
    volumes:
      - database-pg:/var/lib/postgresql/data

networks:
  backend:
    driver: bridge

volumes:
  database-pg: